# Data Science niestacjonarne
## Bartosz Lewandowski
### nr albumu 24840
Lista wylosowanych zadań: [3, 4, 5, 8, 9, 11, 17, 20, 23, 25, 26, 31, 35]

In [1]:
def numberChecker(variable):
    try:
        assert isinstance(variable, float) or isinstance(variable, int)
        return True
    
    except AssertionError:
        print("Podana wartość nie jest liczbą!!!")
        return False
    
def positiveIntegerCheck(variable):
    try:
        assert isinstance(variable, int)  and variable >= 0
        return True
    
    except AssertionError:
        print("Podana wartość nie jest liczbą całkowitą lub nie jest liczbą nieujemną!!!")
        return False

### Zadanie 3.
Utwórz skrypt do zamiany kilometrów na mile i na odwrót.

In [50]:
def mileKilometreConverter(miles):
    if numberChecker(miles):
        return miles*1.60934

def kilometreMileConverter(km):
    if numberChecker(km):
        return km*0.621371
        
print(kilometreMileConverter(212))
print(mileKilometreConverter(21))

131.730652
33.79614


### Zadanie 4.
Utwórz skrypt do znajdowania miejsc zerowych trójmianu kwadratowego.

In [67]:
def zeroOfFunction(a,b,c):
    delta = b**2 - 4*a*c
    if delta > 0:
        return (-b-delta**0.5)/2*a, (-b+delta**0.5)/2*a
    elif delta == 0:
        return -b/2*a
    else:
        return None
    
print(zeroOfFunction(1,2,1))

-1.0


### Zadanie 5.
Utwórz skrypt, który będzie komunikować, czy wprowadzona liczba jest dodatnia czy nie.

In [51]:
#zwraca True dla parzystej, False dla nieparzystej liczby
#w przypadku podaniu zmiennej typu float, liczba jest konwertowana
#na liczbę całkowitą.

def parityCheck(number):
    if numberChecker(number):
        number = int(number)
        return not(bool(number%2))
        
print(parityCheck(112131231312))
print(parityCheck(112131231311))

True
False


### Zadanie 8.
W klasie przeprowadzono sprawdzian, za który uczniowie mogli otrzymać maksymalnie 40 punktów. Skala ocen w szkole jest następująca: 0-39% - ndst, 40-49% - dop, 50-69% - dst, 70-84% - db, 85-99% - bdb, 100% - cel. Utwórz skrypt z interfejsem tekstowym, który na podstawie podanej liczby punktów ze sprawdzianu wyświetli ocenę jaka się należy (skorzystaj z konstrukcji if, elif, else)

In [53]:
def score(points):
    try:
        if not numberChecker(points): return
        assert 0 <= points <= 100

        return 'cel' if points == 100 else 'bdb' if points >= 85 else 'db' if points >= 70 else \
                'dst' if points >= 50 else 'dop' if points >= 40 else 'ndst'
    
    except AssertionError:
        print("Podana wartość nie jest liczbą lub podana liczba nie zawiera się w przedziale <0;100>")
        
print(score(121))
print(score(-25))
print(score('dwadziescia'))
print(score(100))
print(score(85))
print(score(70))
print(score(55))
print(score(45))
print(score(1))

Podana wartość nie jest liczbą lub podana liczba nie zawiera się w przedziale <0;100>
None
Podana wartość nie jest liczbą lub podana liczba nie zawiera się w przedziale <0;100>
None
None
cel
bdb
db
dst
dop
ndst


### Zadanie 9.
Utwórz skrypt z interfejsem tekstowym, który wyliczy sumę n kolejnych liczb (użytkownik podaje pierwszą i ostatnią liczbę sumy). Uwaga - w zadaniu należy zbudować funkcję własną realizującą dane zadanie

In [55]:
def sequenceSum(begin,end):
        if numberChecker(begin) and numberChecker(end):
            begin, end = int(begin), int(end)
            return sum(list(range(begin,end+1)))
    
print(sequenceSum(-0,10))

55


### Zadanie 11.
Utwórz skrypt z interfejsem tekstowym który obliczy silnię od danego argumentu. Wykonać zadanie na dwa sposoby - iteracyjnie i rekurencyjnie.


In [85]:
from functools import reduce 

def factorialNorm(number):
    if positiveIntegerCheck(number):
        return reduce((lambda x, y: x * y), list(range(1,number+1)))  if number != 0 else 0
    
def factorialReq(number):
    if not positiveIntegerCheck(number): return
    if number == 1: return 1
    return number*factorialReq(number-1)

print(factorialReq(-2))
print(factorialReq(6))
print(factorialNorm(-2))
print(factorialNorm(6))

Podana wartość nie jest liczbą lub nie jest liczbą nieujemną!!!
None
720
Podana wartość nie jest liczbą lub nie jest liczbą nieujemną!!!
None
720


### Zadanie 17.
Utwórz funkcję, która będzie generować listy danych do wykreślenia w oparciu o:
<ol>
<li>fukcję liniową ax+b</li>
<li>funkcję kwadratową ax^2+bx+c</li>
<li>funkcję odwrotnie-potęgową a/x^n</li>
</ol>
Każda z fukcji powinna przyjmować parametry równania, natomiast zwracać powinna dwie listy - x i y, które następnie będzie można wykreślić na wykresie


In [90]:
import numpy as np

def linearFunciton(a,b):
    if not (numberChecker(a) and numberChecker(b)): return None
    x = np.arange(-20,20,0.1)
    return x, list(map(lambda y: a*y+b, x))

def squareFunction(a,b,c):
    if not (numberChecker(a) and numberChecker(b) and numberChecker(c)): return None
    x = np.arange(-20,20,0.1)
    return x, list(map(lambda y: a*y**2+b*y+c, x))


def inverseExponentialFunction(a,n):
    if not (numberChecker(a) and numberChecker(n)): return None
    x = list(np.arange(-2,2,0.5))
    if 0 in x: x.remove(0)
    return x, list(map(lambda y: a/(y**n), x))

inverseExponentialFunction(1,1)

([-2.0, -1.5, -1.0, -0.5, 0.5, 1.0, 1.5],
 [-0.5, -0.6666666666666666, -1.0, -2.0, 2.0, 1.0, 0.6666666666666666])

### Zadanie 20.
Korzystając ze słownika, utwórz funkcję, która będzie zwracać tłumaczenia nazw miesięcy z języka polskiego na angielski.

In [64]:
def monthDictionary(month):
    if isinstance(month, str): month = month.lower()
    dict = {'styczeń':'January',
    'luty':'February',
    'marzec':'March',
    'kwiecień':'April',
    'maj':'May',
    'czerwiec':'June',
    'lipiec':'July',
    'sierpień':'August',
    'wrzesień':'September',
    'październik':'October',
    'listopad':'November',
    'grudzień':'December'}
    return dict[month] if month in dict else 0

print(monthDictionary('Grudzień'))
print(monthDictionary('lutyas'))

December
0


### Zadanie 23.
Utwórz funkcję, która jako argument będzie przyjmować listę liczb zmiennoprzecinkowych, a jej wynikiem będzie dominanta (moda). Skorzystaj z obiektu Counter i jego metody most_common z pakietu collections.

In [80]:
from collections import Counter

def checkList(listOfElements):
    return all(isinstance(element, (int, float)) for element in listOfElements)

def mode(listOfNumbers):
    try:
        assert checkList(listOfNumbers)
        return Counter(listOfNumbers).most_common(1)[0][0]
    
    except AssertionError:
        print("Niepoprawny typ elementów listy.")

print(mode([1,2,3,4,5,5,5,5,6,5,4,3,2]))

5


### Zadanie 25.
Utwórz fukcję, która jako argument będzie przyjmować listę liczb zmiennoprzecinkowych, a jej wynikiem będzie drugi moment centralny (wariancja).

In [51]:
def checkList(listOfElements):
    return all(isinstance(element, (int, float)) for element in listOfElements)


def skewness(listOfNumbers):
    try:
        assert checkList(listOfNumbers)
        average = sum(listOfNumbers)/len(listOfNumbers)
        return round(sum(map(lambda x: (x-average)**2 ,listOfNumbers))/len(listOfNumbers),3)
    
    except AssertionError:
        print("Niepoprawny typ elementów listy.")
    
    
skewness([12, 1.32, 1, 1.12])

22.1

### Zadanie 26.
Utwórz funkcję, która jako argument będzie przyjmować listę liczb zmiennoprzecinkowych, a jej wynikiem będzie trzeci moment centralny (skośność)

In [50]:
def checkList(listOfElements):
    return all(isinstance(element, (int, float)) for element in listOfElements)


def skewness(listOfNumbers):
    try:
        assert checkList(listOfNumbers)
        average = sum(listOfNumbers)/len(listOfNumbers)
        return round(sum(map(lambda x: (x-average)**3 ,listOfNumbers))/len(listOfNumbers),3)
    
    except AssertionError:
        print("Niepoprawny typ elementów listy.")
    
    
skewness([12, 1.32, 1, 1.12])

119.75

### Zadanie 31.
Korzystając z instrukcji np.random.choice oraz reshape z pakietu numpy stworzyć funkcję generują macierz kwadratową stopnia N wypełnioną wartościami 0 i 255 w losowy sposób

In [34]:
import numpy as np

N = int(input('Proszę wprowadzić wymiar macierzy kwadratowej:'))
randomNumbers = np.random.choice([0,255], N*N, p=[0.7, 0.3]).reshape(N,N)
print(randomNumbers)

Proszę wprowadzić wymiar macierzy kwadratowej:10
[[  0   0 255 255   0 255 255   0   0   0]
 [  0   0   0 255   0 255   0   0 255 255]
 [  0   0   0   0   0   0   0 255 255   0]
 [  0 255   0   0   0   0 255   0   0   0]
 [  0   0   0 255   0   0 255   0   0   0]
 [  0 255   0   0   0   0 255   0   0   0]
 [  0   0   0 255   0   0 255 255   0   0]
 [  0   0 255   0   0   0   0   0   0 255]
 [255   0   0 255   0 255   0   0   0 255]
 [  0 255   0   0   0   0   0   0   0   0]]


### Zadanie 35.
Utwórz klasę Prostokąt, a następnie na jej podstawie (korzystając z mechanizmu dziedziczenia) utwórz klasę Kwadrat.

In [24]:
class Rectangle():
    def __init__(self, a=0, b=0):
        self._flag = False
        
        self._a = a if numberChecker(a) else 0
        self._b = b if numberChecker(b) else 0
        
        if self._a and self._b:
            self._flag = True
            
    def __str__(self):
        return f'side a={self._a}, side b={self._b}'
    
    def area(self):
        if self._flag:
            return self._a * self._b
    
    def perimeter(self):
        if self._flag:
            return 2 * self._a + 2 * self._b
    
    
class Square(Rectangle):
    def __init__(self, a=0):
        super().__init__(a,a)
        
    def __str__(self):
        return f'side a={self._a}'
    
    
rect = Rectangle(2,3)
sq = Square(3)

print(rect)
print(f'Pole prostokata = {rect.area()}')
print(f'Obwod prostokata = {rect.perimeter()}')

print(sq)
print(f'Pole prostokata = {sq.area()}')
print(f'Obwod prostokata = {sq.perimeter()}')
    
sqaa = Square('ewaea')

side a=2, side b=3
Pole prostokata = 6
Obwod prostokata = 10
side a=3
Pole prostokata = 9
Obwod prostokata = 12
Podana wartość nie jest liczbą!!!
Podana wartość nie jest liczbą!!!
